### ISSUE TITLE
Need to scope the social auth

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/suggestive#22]
https://twitter.com/mattcroftuk/status/793100899119992833

![mattcroftuk_2016-oct-31](https://cloud.githubusercontent.com/assets/151829/19858395/a8ed349c-9f57-11e6-9ffe-58ff8c10b1fc.jpg)

Need to scope social auth to just get user id/name/email

**Comment by michaeldyrynda** [comment]
Also, are you actually getting email addresses back? Twitter makes you send in a [manual request](https://dev.twitter.com/rest/reference/get/account/verify_credentials) to justify the need for it, otherwise they just give you an empty result back.

In either case, it should be sufficient to modify the app permissions (dev.twitter.com) to juse be read only.

**Comment by mattstauffer** [comment]
ahhhhhh
@michaeldyrynda thanks! Tried that out.
